version: "3"

services:
  app:
    build: . #contruye la imagen a partir del contexto . (directorio actual)
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3010:3000"
    volumes:
      - .:/usr/src # copia el directorio actual del local a la carpeta /usr/src de la imagen
      - /usr/src/node_modules # evita que se pise el directorio node_modules de la imagen al hacer la copia anterior
  db:
    image: mongo

  lb:
    image: dockercloud/haproxy
    depends_on:
      - app
    ports:
      - 80:80
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
